# https://golangci-lint.run/usage/configuration/#config-file
linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - revive
    - staticcheck
    - govet
    - forbidigo
    - exhaustive
    - godox
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - misspell
    - gosec
linters-settings:
  godox:
    keywords:
      - FIXME # marks TODOs that must be fixed before merging
  revive:
    severity: error
    confidence: 0.8
    enable-all-rules: true
    rules:
      # Disabled rules
      - name: add-constant
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: unchecked-type-assertion
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: empty-lines
        disabled: true
      - name: confusing-naming
        disabled: true
      - name: bare-return
        disabled: true
      - name: flag-parameter
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: function-length
        disabled: true
      - name: unused-parameter
        disabled: true
      - name: deep-exit
        disabled: true
      - name: line-length-limit
        disabled: true
issues:
  exclude-dirs:
    - ui
    - assets
    - .git
    - cert
    - bin
    - internal/frontend/gen
    - internal/service/scheduler/filenotify
  exclude-rules:
    - path: _test\.go|tests/.+\.go
      linters:
        - err113 # like err = errors.New("test error")
        - gosec
        - add-constant
        - revive
