version: "3.9"
services:
    # init container updates permission
    init:
        image: "ghcr.io/dagu-dev/dagu:latest"
        user: root
        volumes:
            - dagu:/home/dagu/.config/dagu
        command: chown -R dagu /home/dagu/.config/dagu/

    # ui server process
    server:
        image: "ghcr.io/dagu-dev/dagu:latest"
        environment:
            - DAGU_PORT=8080
            - DAGU_DAGS=/home/dagu/.config/dagu/dags
        restart: unless-stopped
        ports:
            - "8080:8080"
        volumes:
            - dagu:/home/dagu/.config/dagu
            - ./dags/:/home/dagu/.config/dagu/dags
        depends_on:
            - init

    # scheduler process
    scheduler:
        image: "ghcr.io/dagu-dev/dagu:latest"
        environment:
            - DAGU_DAGS=/home/dagu/.config/dagu/dags
        restart: unless-stopped
        volumes:
            - dagu:/home/dagu/.config/dagu
            - ./dags/:/home/dagu/.config/dagu/dags
        command: dagu scheduler
        depends_on:
            - init

volumes:
    dagu: {}
