name: Release
on:
  create:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Installing swagger
        run: |
          go install github.com/go-swagger/go-swagger/cmd/swagger@latest

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up yarn
        run: npm install --global yarn

      - name: Check out code
        uses: actions/checkout@v3

      - name: Yarn install
        run: yarn install
        working-directory: ui

      - name: Build web UI
        run: yarn build
        working-directory: ui

      - name: Copy web assets
        run: |
          cp ui/dist/* ./internal/service/frontend/assets/

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.DAGU_GITHUB_TOKEN}}
