name: Release
on:
  create:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Installing protoc-gen-go
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Set up yarn
        run: npm install --global yarn

      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Yarn install
        run: yarn install
        working-directory: ui

      - name: Build web UI
        run: yarn build
        working-directory: ui

      - name: Copy web assets
        run: |
          cp ui/dist/*.js ./service/frontend/http/handler/assets/
          cp ui/dist/*.woff ./service/frontend/http/handler/assets/
          cp ui/dist/*.woff2 ./service/frontend/http/handler/assets/

      - name: Run protoc
        run: |
          protoc -I=./ --go_out=./internal ./internal/proto/*.proto

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{secrets.DAGU_GITHUB_TOKEN}}